<?php

$config['serverversion'] = "151";


//DISCORD CONFIGS
$config['discord'] = array(
    "channel_id" => "",
    "token" => "",
    "webhook_url" => ""
);

//SERVER CONNECTION CONFIGS
$config["ip"] = "127.0.0.1";
$config['ports'] = [
    "client" => 29000,
    "gamedbd" => 29400,
    "gdeliveryd" => 29100,
    "gacd" => 29300,
];

//PROTOCOL SETTINGS, DO NOT CHANGE.
$config['s_block'] = false;
$config['s_readtype'] = 3;
$config['maxbuffer'] = 65536;
$config['version'] = 101;
$config['code'] = [
    'getUserRoles' => 3401,
    'getRoleBase' => 3013,
    'renameRole' => 3404,
];


$config['protocolo151'] = [
    'code' => array(
        'getOnlineList' => 352,
        'getUserRoles' => 3401,
        'getRole' => 8003,
        'putRole' => 8002,
        'getUser' => 3002,
        'getRoleStatus' => 3015,
        'getRoleBase' => 3013,
        'getRoleInventory' => 3053,
        'getRoleEquipment' => 3017,
        'getRoleStoreHouse' => 3027,
        'getRoleTask' => 3019,
        'sendMail' => 4214,
        'worldChat' => 120,
        'chat2player' => 96,
        'forbidAcc' => 5035,
        'forbidRole' => 360,
        'muteAcc' => 362,
        'muteRole' => 356,
        'getRoleid' => 3033,
        'renameRole' => 3404,
        'getTerritory' => 863,
        'getRoleFriend' => 201,
        'AddFaction' => 4600,
        'DelFaction' => 4601,
        'getFactionInfo' => 4606,
        'getUserExtraInfo' => 384,
        'getUserFaction' => 4607,
        'getFactionDetail' => 4608,
        'FactionUpgrade' => 4610,
        'GFactionFortressDetail' => 4404,
        'Debug' => 873,
        'sendGold' => 521,
    ),
    'role' => array(
        'base' => array(
            'version' => 'byte',
            'id' => 'int',
            'name' => 'name',
            'race' => 'int',
            'cls' => 'int',
            'gender' => 'byte',
            'custom_data' => 'octets',
            'config_data' => 'octets',
            'custom_stamp' => 'int',
            'status' => 'byte',
            'delete_time' => 'int',
            'create_time' => 'int',
            'lastlogin_time' => 'int',
            'forbidcount' => 'cuint',
            'forbid' => array(
                'type' => 'byte',
                'time' => 'int',
                'createtime' => 'int',
                'reason' => 'name',
            ),
            'help_states' => 'octets',
            'spouse' => 'int',
            'userid' => 'int',
            'cross_data' => 'octets',
            'reserved2' => 'byte',
            'reserved3' => 'byte',
            'reserved4' => 'byte',
        ),
        'status' => array(
            'version' => 'byte',
            'level' => 'int',
            'level2' => 'int',
            'exp' => 'int',
            'sp' => 'int',
            'pp' => 'int',
            'hp' => 'int',
            'mp' => 'int',
            'posx' => 'float',
            'posy' => 'float',
            'posz' => 'float',
            'worldtag' => 'int',
            'invader_state' => 'int',
            'invader_time' => 'int',
            'pariah_time' => 'int',
            'reputation' => 'int',
            'custom_status' => 'octets',
            'filter_data' => 'octets',
            'charactermode' => 'octets',
            'instancekeylist' => 'octets',
            'dbltime_expire' => 'int',
            'dbltime_mode' => 'int',
            'dbltime_begin' => 'int',
            'dbltime_used' => 'int',
            'dbltime_max' => 'int',
            'time_used' => 'int',
            'dbltime_data' => 'octets',
            'storesize' => 'short',
            'petcorral' => 'octets',
            'property' => 'octets',
            'var_data' => 'octets',
            'skills' => 'octets',
            'storehousepasswd' => 'octets',
            'waypointlist' => 'octets',
            'coolingtime' => 'octets',
            'npc_relation' => 'octets',
            'multi_exp_ctrl' => 'octets',
            'storage_task' => 'octets',
            'faction_contrib' => 'octets',
            'force_data' => 'octets',
            'online_award' => 'octets',
            'profit_time_data' => 'octets',
            'country_data' => 'octets',
            'king_data' => 'octets',
            'meridian_data' => 'octets',
            'extraprop' => 'octets',
            'title_data' => 'octets',
            'reincarnation_data' => 'octets',
            'realm_data' => 'octets',
            'reserved2' => 'byte',
            'reserved3' => 'byte',
        ),
        'pocket' => array(
            'icapacity' => 'int',
            'timestamp' => 'int',
            'money' => 'int',
            'invcount' => 'cuint',
            'inv' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'reserved6' => 'int',
            'reserved7' => 'int',
        ),
        'equipment' => array(
            'eqpcount' => 'cuint',
            'eqp' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
        ),
        'storehouse' => array(
            'icapacity' => 'int',
            'money' => 'int',
            'storecount' => 'cuint',
            'store' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'size1' => 'byte',
            'size2' => 'byte',
            'dresscount' => 'cuint',
            'dress' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'materialcount' => 'cuint',
            'material' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'size3' => 'byte',
            'generalcardcount' => 'cuint',
            'generalcard' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'reserved' => 'short',
        ),
        'task' => array(
            'task_data' => 'octets',
            'task_complete' => 'octets',
            'task_finishtime' => 'octets',
            'task_inventorycount' => 'cuint',
            'task_inventory' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
        ),
    ),
    'octet' => array(
        'var_data' => array(
            'version' => 'lint',
            'pk_count' => 'lint',
            'pvp_cooldown' => 'lint',
            'pvp_flag' => 'byte',
            'dead_flag' => 'byte',
            'is_drop' => 'byte',
            'resurrect_state' => 'byte',
            'resurrect_exp_reduce' => 'float',
            'instance_hash_key1' => 'lint',
            'instance_hash_key2' => 'lint',
            'trashbox_size' => 'lint',
            'last_instance_timestamp' => 'lint',
            'last_instance_tag' => 'lint',
            'last_instance_pos' => array(
                'x' => 'float',
                'y' => 'float',
                'z' => 'float',
            ),
            'dir' => 'lint',
            'resurrect_hp_factor' => 'float',
            'resurrect_mp_factor' => 'float',
        ),
        'property' => array(
            'con' => 'lint',
            'int' => 'lint',
            'str' => 'lint',
            'dex' => 'lint',
            'max_hp' => 'lint',
            'max_mp' => 'lint',
            'hp_gen' => 'lint',
            'mp_gen' => 'lint',
            'walk_speed' => 'float2',
            'run_speed' => 'float2',
            'swim_speed' => 'float2',
            'fly_speed' => 'float2',
            'attack' => 'lint',
            'damage_low' => 'lint',
            'damage_high' => 'lint',
            'attack_speed' => 'lint',
            'attack_range' => 'float2',
            'damage_low1' => array(
                1 => 'int',
                2 => 'int',
                3 => 'int',
                4 => 'int',
                5 => 'int'
            ),
            'damage_high1' => array(
                1 => 'int',
                2 => 'int',
                3 => 'int',
                4 => 'int',
                5 => 'int'
            ),
            'damage_magic_low' => 'lint',
            'damage_magic_high' => 'lint',
            'resistance' => array(
                1 => 'int',
                2 => 'int',
                3 => 'int',
                4 => 'int',
                5 => 'int'
            ),
            'defense' => 'lint',
            'armor' => 'lint',
            'max_ap' => 'lint',
        ),
        'force_data' => array(
            'cur_force_id' => 'int',
            'forcecount' => 'cuint',
            'force' => array(
                'force_id' => 'int',
                'reputation' => 'int',
                'contribution' => 'int',
            ),
        ),
        'faction_contrib' => array(
            'consume_contrib' => 'lint',
            'exp_contrib' => 'lint',
            'cumulate_contrib' => 'lint',
        ),
        'title_data' => array(
            'cur_title_id' => 'lshort',
            'titlecount' => 'cuint',
            'unk1' => 'lshort',
            'title' => array(
                'title_id' => 'short',
            ),
        ),
    ),
    'user' => array(
        'roles' => array(
            'count' => 'cuint',
            'roles' => array(
                'id' => 'int',
                'name' => 'name',
            )
        ),
        'info' => array(
            'logicuid' => 'int',
            'rolelist' => 'int',
            'cash' => 'int',
            'money' => 'int',
            'cash_add' => 'int',
            'cash_buy' => 'int',
            'cash_sell' => 'int',
            'cash_used' => 'int',
            'add_serial' => 'int',
            'use_serial' => 'int',
            'exp_logcount' => 'cuint',
            'exg_log' => array(
                'tid' => 'int',
                'time' => 'int',
                'result' => 'short',
                'volume' => 'short',
                'cost' => 'int',
            ),
            'addiction' => 'octets',
            'cash_password' => 'octets',
            'autolockcount' => 'cuint',
            'autolock' => array(
                'key' => 'int',
                'value' => 'int',
            ),
            'status' => 'byte',
            'forbidcount' => 'cuint',
            'forbid' => array(
                'type' => 'byte',
                'time' => 'int',
                'createtime' => 'int',
                'reason' => 'name',
            ),
            'reference' => 'octets',
            'consume_reward' => 'octets',
            'taskcounter' => 'octets',
            'cash_sysauction' => 'octets',
            'login_record' => 'octets',
            'mall_consumption' => 'octets',
            'reserved32' => 'short',
        ),
    ),
    'RoleList' => array(
        'localsid' => 'int',
        'handler' => 'int',
        'userscount' => 'cuint',
        'users' => array(
            'userid' => 'int',
            'roleid' => 'int',
            'linkid' => 'int',
            'localsid' => 'int',
            'gsid' => 'int',
            'status' => 'byte',
            'name' => 'name',
        ),
    ),
    'FriendList' => array(
        'groupinfocount' => 'cuint',
        'groupinfo' => array(
            'gid' => 'byte',
            'name' => 'name',
        ),
        'friendinfocount' => 'cuint',
        'friendinfo' => array(
            'rid' => 'int',
            'cls' => 'byte',
            'gender' => 'byte',
            'name' => 'name'
        ),
    ),
    'FactionInfo' => array(
        'fid' => 'int',
        'name' => 'name',
        'level' => 'byte',
        'master' => array(
            'roleid' => 'int',
            'role' => 'byte',
        ),
        'membercount' => 'cuint',
        'member' => array(
            'roleid' => 'int',
            'role' => 'byte',
        ),
        'announce' => 'name',
        'sysinfo' => 'octets',
    ),
    'getUserExtraInfo' => array(
        'opcode' => 'cuint',
        'length' => 'cuint',
        'always' => 'int',
        'retcode' => 'int',
        'count' => 'cuint',
        'roleid' => 'int',
        'level' => 'int',
        'login_ip' => 'int',
        'cash_add' => 'int',
        'mall_consumption' => 'int',
        'avg_online_time' => 'int',
    ),
    'FactionDetail' => array(
        'fid' => 'int',
        'name' => 'name',
        'level' => 'byte',
        'master' => 'int',
        'announce' => 'name',
        'sysinfo' => 'octets',
        'membercount' => 'cuint',
        'member' => array(
            'roleid' => 'int',
            'level' => 'byte',
            'occupation' => 'byte',
            'froleid' => 'byte',
            'login_day' => 'short',
            'online_status' => 'byte',
            'name' => 'name',
            'nickname' => 'name',
            'contrib' => 'int',
            'delayexpel' => 'byte',
            'expeltime' => 'int',
        ),
        'last_op_time' => 'int',
        'alliancecount' => 'cuint',
        'alliance' => array(
            'fid' => 'int',
            'end_time' => 'int',
        ),
        'hostilecount' => 'cuint',
        'hostile' => array(
            'fid' => 'int',
            'end_time' => 'int',
        ),
        'applycount' => 'cuint',
        'apply' => array(
            'type' => 'int',
            'fid' => 'int',
            'end_time' => 'int',
        ),
    ),
    'RawRead' => array(
        'handle' => 'octets',
        'Rawcount' => 'cuint',
        'Raw' => array(
            'key' => 'octets',
            'value' => 'octets',
        )
    ),
    'GTerritoryDetail' => array(
        'Territorycount' => 'cuint',
        'Territory' => array(
            'id' => 'short',
            'level' => 'short',
            'owner' => 'int',
            'occupy_time' => 'int',
            'challenger' => 'int',
            'deposit' => 'int',
            'cutoff_time' => 'int',
            'battle_time' => 'int',
            'bonus_time' => 'int',
            'color' => 'int',
            'status' => 'int',
            'timeout' => 'int',
            'maxbonus' => 'int',
            'challenge_time' => 'int',
            'challengerdetails' => 'octets',
            'reserved1' => 'byte',
            'reserved2' => 'byte',
            'reserved3' => 'byte',
        ),
    ),
    'FactionFortressDetail' => array(
        'factionid' => 'int',
        'info' => array(
            'level' => 'int',
            'exp' => 'int',
            'exp_today' => 'int',
            'exp_today_time' => 'int',
            'tech_point' => 'int',
            'technology' => 'octets',
            'material' => 'octets',
            'building' => 'octets',
            'common_value' => 'octets',
            'actived_spawner' => 'octets',
            'reserved11' => 'byte',
            'reserved12' => 'short',
            'reserved2' => 'int',
            'reserved3' => 'int',
        ),
        'info2' => array(
            'health' => 'int',
            'offense_faction' => 'int',
            'offense_starttime' => 'int',
            'offense_endtime' => 'int',
            'challenge_listcount' => 'cuint',
            'challenge_list' => array(
                'item' => 'int'
            ),
            'reserved1' => 'int',
            'reserved2' => 'int',
            'reserved3' => 'int',
        ),
        'reserved1' => 'int',
        'reserved2' => 'int',
        'reserved3' => 'int',
        'reserved4' => 'int',
        'reserved5' => 'int',
    ),
    'getUserFaction' => array(
        'rid' => 'int',
        'name' => 'name',
        'fid' => 'int',
        'cls' => 'byte',
        'role' => 'byte',
        'delayexpel' => 'octets',
        'extend' => 'octets',
        'nickname' => 'name',
    )
];

$config['protocolo153'] = [
    'code' => array(
        'getOnlineList' => 352,
        'getUserRoles' => 3401,
        'getRole' => 8003,
        'putRole' => 8002,
        'getUser' => 3002,
        'getRoleStatus' => 3015,
        'getRoleBase' => 3013,
        'getRoleInventory' => 3053,
        'getRoleEquipment' => 3017,
        'getRoleStoreHouse' => 3027,
        'getRoleTask' => 3019,
        'sendMail' => 4214,
        'worldChat' => 120,
        'chat2player' => 96,
        'forbidAcc' => 5035,
        'forbidRole' => 360,
        'muteAcc' => 362,
        'muteRole' => 356,
        'getRoleid' => 3033,
        'renameRole' => 3404,
        'getTerritory' => 863,
        'setTerritory' => 864,
        'getRoleFriend' => 201,
        'AddFaction' => 4600,
        'DelFaction' => 4601,
        'getFactionInfo' => 4606,
        'getUserExtraInfo' => 384,
        'getUserFaction' => 4607,
        'getFactionDetail' => 4608,
        'FactionUpgrade' => 4610,
        'GFactionFortressDetail' => 4404,
        'Debug' => 873,
        'sendGold' => 521,
    ),
    'role' => array(
        'base' => array(
            'version' => 'byte',
            'id' => 'int',
            'name' => 'name',
            'race' => 'int',
            'cls' => 'int',
            'gender' => 'byte',
            'custom_data' => 'octets',
            'config_data' => 'octets',
            'custom_stamp' => 'int',
            'status' => 'byte',
            'delete_time' => 'int',
            'create_time' => 'int',
            'lastlogin_time' => 'int',
            'forbidcount' => 'cuint',
            'forbid' => array(
                'type' => 'byte',
                'time' => 'int',
                'createtime' => 'int',
                'reason' => 'name',
            ),
            'help_states' => 'octets',
            'spouse' => 'int',
            'userid' => 'int',
            'cross_data' => 'octets',
            'reserved2' => 'byte',
            'reserved3' => 'byte',
            'reserved4' => 'byte',
        ),
        'status' => array(
            'version' => 'byte',
            'level' => 'int',
            'level2' => 'int',
            'exp' => 'int',
            'sp' => 'int',
            'pp' => 'int',
            'hp' => 'int',
            'mp' => 'int',
            'posx' => 'float',
            'posy' => 'float',
            'posz' => 'float',
            'worldtag' => 'int',
            'invader_state' => 'int',
            'invader_time' => 'int',
            'pariah_time' => 'int',
            'reputation' => 'int',
            'custom_status' => 'octets',
            'filter_data' => 'octets',
            'charactermode' => 'octets',
            'instancekeylist' => 'octets',
            'dbltime_expire' => 'int',
            'dbltime_mode' => 'int',
            'dbltime_begin' => 'int',
            'dbltime_used' => 'int',
            'dbltime_max' => 'int',
            'time_used' => 'int',
            'dbltime_data' => 'octets',
            'storesize' => 'short',
            'petcorral' => 'octets',
            'property' => 'octets',
            'var_data' => 'octets',
            'skills' => 'octets',
            'storehousepasswd' => 'octets',
            'waypointlist' => 'octets',
            'coolingtime' => 'octets',
            'npc_relation' => 'octets',
            'multi_exp_ctrl' => 'octets',
            'storage_task' => 'octets',
            'faction_contrib' => 'octets',
            'force_data' => 'octets',
            'online_award' => 'octets',
            'profit_time_data' => 'octets',
            'country_data' => 'octets',
            'king_data' => 'octets',
            'meridian_data' => 'octets',
            'extraprop' => 'octets',
            'title_data' => 'octets',
            'reincarnation_data' => 'octets',
            'realm_data' => 'octets',
            'reserved2' => 'byte',
            'reserved3' => 'byte',
        ),
        'pocket' => array(
            'icapacity' => 'int',
            'timestamp' => 'int',
            'money' => 'int',
            'invcount' => 'cuint',
            'inv' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'reserved6' => 'int',
            'reserved7' => 'int',
        ),
        'equipment' => array(
            'eqpcount' => 'cuint',
            'eqp' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
        ),
        'storehouse' => array(
            'icapacity' => 'int',
            'money' => 'int',
            'storecount' => 'cuint',
            'store' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'size1' => 'byte',
            'size2' => 'byte',
            'dresscount' => 'cuint',
            'dress' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'materialcount' => 'cuint',
            'material' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'size3' => 'byte',
            'generalcardcount' => 'cuint',
            'generalcard' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
            'reserved' => 'short',
        ),
        'task' => array(
            'task_data' => 'octets',
            'task_complete' => 'octets',
            'task_finishtime' => 'octets',
            'task_inventorycount' => 'cuint',
            'task_inventory' => array(
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int'
            ),
        ),
    ),
    'octet' => array(
        'var_data' => array(
            'version' => 'lint',
            'pk_count' => 'lint',
            'pvp_cooldown' => 'lint',
            'pvp_flag' => 'byte',
            'dead_flag' => 'byte',
            'is_drop' => 'byte',
            'resurrect_state' => 'byte',
            'resurrect_exp_reduce' => 'float',
            'instance_hash_key1' => 'lint',
            'instance_hash_key2' => 'lint',
            'trashbox_size' => 'lint',
            'last_instance_timestamp' => 'lint',
            'last_instance_tag' => 'lint',
            'last_instance_pos' => array(
                'x' => 'float',
                'y' => 'float',
                'z' => 'float',
            ),
            'dir' => 'lint',
            'resurrect_hp_factor' => 'float',
            'resurrect_mp_factor' => 'float',
        ),
        'property' => array(
            'con' => 'lint',
            'int' => 'lint',
            'str' => 'lint',
            'dex' => 'lint',
            'max_hp' => 'lint',
            'max_mp' => 'lint',
            'hp_gen' => 'lint',
            'mp_gen' => 'lint',
            'walk_speed' => 'float2',
            'run_speed' => 'float2',
            'swim_speed' => 'float2',
            'fly_speed' => 'float2',
            'attack' => 'lint',
            'damage_low' => 'lint',
            'damage_high' => 'lint',
            'attack_speed' => 'lint',
            'attack_range' => 'float2',
            'damage_low1' => array(
                1 => 'int',
                2 => 'int',
                3 => 'int',
                4 => 'int',
                5 => 'int'
            ),
            'damage_high1' => array(
                1 => 'int',
                2 => 'int',
                3 => 'int',
                4 => 'int',
                5 => 'int'
            ),
            'damage_magic_low' => 'lint',
            'damage_magic_high' => 'lint',
            'resistance' => array(
                1 => 'int',
                2 => 'int',
                3 => 'int',
                4 => 'int',
                5 => 'int'
            ),
            'defense' => 'lint',
            'armor' => 'lint',
            'max_ap' => 'lint',
        ),
        'force_data' => array(
            'cur_force_id' => 'int',
            'forcecount' => 'cuint',
            'force' => array(
                'force_id' => 'int',
                'reputation' => 'int',
                'contribution' => 'int',
            ),
        ),
        'faction_contrib' => array(
            'consume_contrib' => 'lint',
            'exp_contrib' => 'lint',
            'cumulate_contrib' => 'lint',
        ),
        'title_data' => array(
            'cur_title_id' => 'lshort',
            'titlecount' => 'cuint',
            'unk1' => 'lshort',
            'title' => array(
                'title_id' => 'short',
            ),
        ),
    ),
    'user' => array(
        'roles' => array(
            'count' => 'cuint',
            'roles' => array(
                'id' => 'int',
                'name' => 'name',
            )
        ),
        'info' => array(
            'logicuid' => 'int',
            'rolelist' => 'int',
            'cash' => 'int',
            'money' => 'int',
            'cash_add' => 'int',
            'cash_buy' => 'int',
            'cash_sell' => 'int',
            'cash_used' => 'int',
            'add_serial' => 'int',
            'use_serial' => 'int',
            'exp_logcount' => 'cuint',
            'exg_log' => array(
                'tid' => 'int',
                'time' => 'int',
                'result' => 'short',
                'volume' => 'short',
                'cost' => 'int',
            ),
            'addiction' => 'octets',
            'cash_password' => 'octets',
            'autolockcount' => 'cuint',
            'autolock' => array(
                'key' => 'int',
                'value' => 'int',
            ),
            'status' => 'byte',
            'forbidcount' => 'cuint',
            'forbid' => array(
                'type' => 'byte',
                'time' => 'int',
                'createtime' => 'int',
                'reason' => 'name',
            ),
            'reference' => 'octets',
            'consume_reward' => 'octets',
            'taskcounter' => 'octets',
            'cash_sysauction' => 'octets',
            'login_record' => 'octets',
            'mall_consumption' => 'octets',
            'reserved32' => 'short',
        ),
    ),
    'RoleList' => array(
        'localsid' => 'int',
        'handler' => 'int',
        'userscount' => 'cuint',
        'users' => array(
            'userid' => 'int',
            'roleid' => 'int',
            'linkid' => 'int',
            'localsid' => 'int',
            'gsid' => 'int',
            'status' => 'byte',
            'name' => 'name',
        ),
    ),
    'FriendList' => array(
        'groupinfocount' => 'cuint',
        'groupinfo' => array(
            'gid' => 'byte',
            'name' => 'name',
        ),
        'friendinfocount' => 'cuint',
        'friendinfo' => array(
            'rid' => 'int',
            'cls' => 'byte',
            'gender' => 'byte',
            'name' => 'name'
        ),
    ),
    'FactionInfo' => array(
        'fid' => 'int',
        'name' => 'name',
        'level' => 'byte',
        'master' => array(
            'roleid' => 'int',
            'role' => 'byte',
        ),
        'membercount' => 'cuint',
        'member' => array(
            'roleid' => 'int',
            'role' => 'byte',
        ),
        'announce' => 'name',
        'sysinfo' => 'octets',
    ),
    'getUserExtraInfo' => array(
        'opcode' => 'cuint',
        'length' => 'cuint',
        'always' => 'int',
        'retcode' => 'int',
        'count' => 'cuint',
        'roleid' => 'int',
        'level' => 'int',
        'login_ip' => 'int',
        'cash_add' => 'int',
        'mall_consumption' => 'int',
        'avg_online_time' => 'int',
    ),
    'FactionDetail' => array(
        'fid' => 'int',
        'name' => 'name',
        'level' => 'byte',
        'master' => 'int',
        'announce' => 'name',
        'sysinfo' => 'octets',
        'membercount' => 'cuint',
        'member' => array(
            'roleid' => 'int',
            'level' => 'byte',
            'occupation' => 'byte',
            'froleid' => 'byte',
            'login_day' => 'short',
            'online_status' => 'byte',
            'name' => 'name',
            'nickname' => 'name',
            'contrib' => 'int',
            'delayexpel' => 'byte',
            'expeltime' => 'int',
        ),
        'last_op_time' => 'int',
        'alliancecount' => 'cuint',
        'alliance' => array(
            'fid' => 'int',
            'end_time' => 'int',
        ),
        'hostilecount' => 'cuint',
        'hostile' => array(
            'fid' => 'int',
            'end_time' => 'int',
        ),
        'applycount' => 'cuint',
        'apply' => array(
            'type' => 'int',
            'fid' => 'int',
            'end_time' => 'int',
        ),
    ),
    'RawRead' => array(
        'handle' => 'octets',
        'Rawcount' => 'cuint',
        'Raw' => array(
            'key' => 'octets',
            'value' => 'octets',
        )
    ),
    'GTerritoryDetail' => array(
        'Territorycount' => 'cuint',
        'Territory' => array(
            'id' => 'short',
            'level' => 'short',
            'owner' => 'int',
            'occupy_time' => 'int',
            'challenger' => 'int',
            'deposit' => 'int',
            'cutoff_time' => 'int',
            'battle_time' => 'int',
            'bonus_time' => 'int',
            'color' => 'int',
            'status' => 'int',
            'timeout' => 'int',
            'maxbonus' => 'int',
            'challenge_time' => 'int',
            'challengerdetails' => 'octets',
            'reserved1' => 'byte',
            'reserved2' => 'byte',
            'reserved3' => 'byte',
        ),
    ),
    'FactionFortressDetail' => array(
        'factionid' => 'int',
        'info' => array(
            'level' => 'int',
            'exp' => 'int',
            'exp_today' => 'int',
            'exp_today_time' => 'int',
            'tech_point' => 'int',
            'technology' => 'octets',
            'material' => 'octets',
            'building' => 'octets',
            'common_value' => 'octets',
            'actived_spawner' => 'octets',
            'reserved11' => 'byte',
            'reserved12' => 'short',
            'reserved2' => 'int',
            'reserved3' => 'int',
        ),
        'info2' => array(
            'health' => 'int',
            'offense_faction' => 'int',
            'offense_starttime' => 'int',
            'offense_endtime' => 'int',
            'challenge_listcount' => 'cuint',
            'challenge_list' => array(
                'item' => 'int'
            ),
            'reserved1' => 'int',
            'reserved2' => 'int',
            'reserved3' => 'int',
        ),
        'reserved1' => 'int',
        'reserved2' => 'int',
        'reserved3' => 'int',
        'reserved4' => 'int',
        'reserved5' => 'int',
    ),
    'getUserFaction' => array(
        'rid' => 'int',
        'name' => 'name',
        'fid' => 'int',
        'cls' => 'byte',
        'role' => 'byte',
        'delayexpel' => 'octets',
        'extend' => 'octets',
        'nickname' => 'name',
    )
];